<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * Template for widget instance js
 *
 * @package     Magenerds\WysiwygWidget
 * @file        instance_editor.phtml
 * @copyright   Copyright (c) 2019 TechDivision GmbH (https://www.techdivision.com)
 * @site        https://www.techdivision.com/
 * @author      Simon Sippert <s.sippert@techdivision.com>
 */

/** @var \Magento\Backend\Block\Template $block */
?>
<script>
    require(['Magento_Ui/js/form/element/wysiwyg']);
</script>
